import argparse
parser = argparse.ArgumentParser(description='eval attacks in PyTorch')
parser.add_argument('--input_dir', default="/data/public/data/nipsgame2017_dataset", type=str, help='the direction of clean image')
parser.add_argument('--input_csv', default="/data/public/data/nipsgame2017_dataset_py/dev_dataset.csv", type=str, help='the direction of clean image csv ')
parser.add_argument('--attack_name', default='mim_sub', type=str, help='attack_name')
parser.add_argument('--beta', default=2, type=float, help='the number of beta')
parser.add_argument('--out_dir', default="/data/huangtao/projects/subsapce-attack", type=str, help='the direction of results.txt')
parser.add_argument('--source_model', default="resnet_v2_50", type=str, help='the source model which crafted AE')
parser.add_argument('--target_model', default="resnet_v2_50", type=str, help='the target_model which test the black-box attack')
parser.add_argument('--device', default=0, type=int, help='gpu device')
parser.add_argument('--use_cuda', default=True, type=bool, help='use gpu or not')
parser.add_argument('--epsilon', default=16/255, type=float, help='the number of epsilon')
parser.add_argument('--iter_num', default=100, type=int, help='the number of iter_num')
parser.add_argument('--decay_factor', default=1, type=float, help='the number of decay_factor')
parser.add_argument('--model_dir', default="/data/huangtao/models/torch_net_weight/", type=str, help='the target_model which test the black-box attack')
parser.add_argument('--Tpt', default=10, type=int, help='the parameter to control the variance of the initial Guassion distribution')
parser.add_argument('--N', default=10, type=int, help='the number of edges of simplex')
parser.add_argument('--S', default=5, type=int, help='the number of share steps')
parser.add_argument('--lr', default=0.01, type=float, help='the learning rate of optimization problem')
parser.add_argument('--N_vt', default=20, type=int, help="the simpling number of variance tuning")
parser.add_argument('--beta_vt', default=1.5, type=float, help='')
parser.add_argument('--len_kernel', default=5, type=int, help='the length of kernel')
parser.add_argument('--nsig', default=3, type=int, help='the nsig of the kernel')
parser.add_argument('--save_img_dir', default="/data/huangtao/projects/subsapce-attack/adv_data", type=str, help='the direct of adv data')
parser.add_argument('--M', default=10, type=int, help='the number of sampling point')
parser.add_argument('--loss', default="ce", type=str, help='the loss function',choices=["ce","logits"])

args = parser.parse_args()
